(() => {
 'use strict';
 const $=id=>document.getElementById(id),players=OrchestraPlayers,audio=new OrchestraAudio(),selected=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)');
 let screen='auditions',paused=false,previewId=null,previewTimer=null,transition=0,stageTime=0,lastFrame=0;
 const canvas=$('stage'),ctx=canvas.getContext('2d'),performancePoses=new Map();
 const band=()=>players.filter(p=>selected.has(p.id));
 function message(text){$('status').textContent=text;}
 function songInfo(){const song=audio.song;$('song-title').textContent=song.title;$('song-detail').textContent=`${song.style.genre} · ${song.bpm} BPM`;$('style').value=audio.style;$('concert-style').value=audio.style;}
 function stopPreview(){clearTimeout(previewTimer);previewId=null;for(const card of document.querySelectorAll('.player')){card.classList.remove('previewing');card.querySelector('.listen').textContent='▷ Listen';card.querySelector('.listen').setAttribute('aria-pressed','false');}}
 function soundError(){audio.stop();message('Sound could not start. Tap Listen or Continue to try again.');}
 function renderSelection(){
  $('count').textContent=`${selected.size} / 5`;$('begin').disabled=selected.size!==5;$('begin').textContent=selected.size===5?'Take the stage ↗':`Choose ${5-selected.size} more ${selected.size===4?'friend':'friends'}`;
  for(const card of document.querySelectorAll('.player')){const chosen=selected.has(card.dataset.id),button=card.querySelector('.choose');card.classList.toggle('selected',chosen);button.textContent=chosen?'✓ Chosen':'+ Choose';button.setAttribute('aria-pressed',String(chosen));button.disabled=selected.size===5&&!chosen;}
  $('seats').replaceChildren();for(let i=0;i<5;i++){const p=band()[i],seat=document.createElement(p?'button':'span');seat.className='seat'+(p?' filled':'');if(p){seat.setAttribute('aria-label',`Remove ${p.name}`);seat.title=`Remove ${p.name}`;const img=document.createElement('img');img.src=`assets/${p.id}.svg`;img.alt='';seat.append(img);seat.onclick=()=>toggle(p.id);}else{seat.textContent=i+1;seat.setAttribute('aria-label',`Empty seat ${i+1}`);}$('seats').append(seat);}
 }
 function toggle(id){if(screen!=='auditions')return;if(selected.has(id))selected.delete(id);else if(selected.size<5)selected.add(id);renderSelection();message(selected.size===5?'Five friends! The conductor is raising the baton…':`${selected.size} of five chosen. Keep listening, or swap anyone out.`);if(selected.size===5)startConcert();}
 async function audition(id){if(screen!=='auditions')return;const was=previewId===id;stopPreview();audio.stop();if(was){message('Preview stopped.');return;}const p=players.find(p=>p.id===id);previewId=id;const card=document.querySelector(`[data-id="${id}"]`);card.classList.add('previewing');card.querySelector('.listen').textContent='■ Stop';card.querySelector('.listen').setAttribute('aria-pressed','true');message(`Listening to ${p.name}: ${p.instrument.toLowerCase()}${audio.muted?' (sound is muted)':''}.`);
  try{await audio.preview(p);}catch{soundError();stopPreview();return;}if(previewId!==id||screen!=='auditions')return;previewTimer=setTimeout(()=>{if(previewId===id){stopPreview();message('Like that sound? Choose them for your orchestra.');}},60/audio.song.bpm*4000+1300);
 }
 async function startConcert(){if(selected.size!==5)return;const arriving=screen!=='concert',request=++transition;stopPreview();performancePoses.clear();screen='concert';paused=false;stageTime=0;$('auditions').hidden=true;$('lineup').hidden=true;$('concert').hidden=false;$('pause-overlay').hidden=true;$('pause').textContent='Pause';$('subtitle').textContent='Your five friends, playing together. Ask the rice conductor for another song anytime.';$('performer-names').replaceChildren();for(const p of band()){const tag=document.createElement('span');tag.textContent=`${p.name} · ${p.instrument}`;$('performer-names').append(tag);}resize();if(arriving){$('concert-title').focus({preventScroll:true});$('concert').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'});}message('Your orchestra is playing. Same friends, endless new songs.');
  try{await audio.play(band());if(request===transition&&(paused||document.hidden))audio.stop();}catch{soundError();pauseConcert();}
 }
 function pauseConcert(){if(screen!=='concert')return;transition++;paused=true;audio.stop();$('pause-overlay').hidden=false;$('pause').textContent='Continue';message('Intermission. Your five friends are waiting.');}
 async function resumeConcert(){if(screen!=='concert')return;paused=false;$('pause-overlay').hidden=true;$('pause').textContent='Pause';message('The conductor counts the band back in.');const request=++transition;try{await audio.play(band());if(request===transition&&(paused||document.hidden))audio.stop();}catch{soundError();pauseConcert();}}
 function editLineup(){transition++;audio.stop();stopPreview();screen='auditions';paused=false;$('concert').hidden=true;$('auditions').hidden=false;$('lineup').hidden=false;$('subtitle').textContent='Five friends. A tiny conductor. A different song every time.';renderSelection();message('Remove a friend to make a swap, or take the same band back on stage.');$('audition-title').scrollIntoView({block:'start',behavior:reduced.matches?'instant':'smooth'});}
 function changeSong(style=audio.style){audio.newSong(style);songInfo();if(screen==='concert')startConcert();else{const p=previewId;stopPreview();audio.stop();message('A new song is ready. Listen to a friend to hear this arrangement.');if(p)audition(p);}}
 for(const [index,style] of SoundGardenComposer.styles.entries()){const option=document.createElement('option');option.value=index;option.textContent=style.genre;$('style').append(option);$('concert-style').append(option.cloneNode(true));}
 for(const p of players){const card=document.createElement('article');card.className='player';card.dataset.id=p.id;const art=document.createElement('div');art.className='player-art';const img=document.createElement('img');img.src=`assets/${p.id}.svg`;img.alt='';art.append(img);const h=document.createElement('h3');h.textContent=p.name;const desc=document.createElement('p');desc.textContent=p.instrument;const actions=document.createElement('div');actions.className='player-actions';const listen=document.createElement('button');listen.className='listen';listen.textContent='▷ Listen';listen.setAttribute('aria-label',`Listen to ${p.name}`);listen.setAttribute('aria-pressed','false');listen.onclick=()=>audition(p.id);const choose=document.createElement('button');choose.className='choose';choose.textContent='+ Choose';choose.setAttribute('aria-label',`Choose ${p.name}`);choose.setAttribute('aria-pressed','false');choose.onclick=()=>toggle(p.id);actions.append(listen,choose);card.append(art,h,desc,actions);$('players').append(card);}
 $('style').onchange=$('concert-style').onchange=e=>changeSong(Number(e.target.value));$('next-song').onclick=()=>changeSong();$('another').onclick=()=>changeSong();$('begin').onclick=startConcert;$('pause').onclick=()=>paused?resumeConcert():pauseConcert();$('resume').onclick=resumeConcert;$('edit').onclick=editLineup;$('replay').onclick=startConcert;
 $('surprise').onclick=()=>{selected.clear();const groups=[['lead','pluck','vocal'],['bass'],['keys','pad'],['drums','wood'],['arp','bell']];for(const roles of groups){const pool=players.filter(p=>roles.includes(p.role));selected.add(pool[Math.floor(Math.random()*pool.length)].id);}renderSelection();startConcert();};
 $('volume').oninput=e=>{audio.volume=Number(e.target.value)/100;audio.applyVolume();};$('mute').onclick=()=>{audio.muted=!audio.muted;audio.applyVolume();$('mute').textContent=audio.muted?'Sound off':'Sound on';$('mute').setAttribute('aria-pressed',String(audio.muted));};
 function leave(){if(screen==='concert')pauseConcert();else{audio.stop();stopPreview();}}document.addEventListener('visibilitychange',()=>{if(document.hidden)leave();});window.addEventListener('blur',leave);window.addEventListener('pagehide',()=>audio.stop());
 function ellipse(x,y,rx,ry,color){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
 function round(x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}}
 function line(points,color,width=2){ctx.beginPath();ctx.moveTo(...points[0]);for(const p of points.slice(1))ctx.lineTo(...p);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.stroke();}
 function drawPerformer(id,x,y,size){let performance=performancePoses.get(id)||{hit:0};if(audio.running&&!paused){performance=audio.performance(id);performancePoses.set(id,performance);}OrchestraPerformers.draw(ctx,id,x,y,size,{time:stageTime,bpm:audio.song.bpm,...performance,still:reduced.matches});}
 function draw(){if(screen!=='concert')return;const w=canvas.width,h=canvas.height;ctx.setTransform(1,0,0,1,0,0);ctx.fillStyle='#dfe4ca';ctx.fillRect(0,0,w,h);const scale=Math.min(w/1000,h/680);ctx.translate((w-1000*scale)/2,(h-680*scale)/2);ctx.scale(scale,scale);
  const sky=ctx.createLinearGradient(0,0,0,500);sky.addColorStop(0,'#bdcdaa');sky.addColorStop(1,'#edf0d8');ctx.fillStyle=sky;ctx.fillRect(0,0,1000,680);
  // Tall curtains, hanging lanterns and an open fan of warm wooden floorboards.
  ctx.fillStyle='#8caa86';ctx.fillRect(0,0,72,505);ctx.fillRect(928,0,72,505);for(let i=0;i<5;i++){round(i*15-7,-20,20,440+(i%2)*18,10,i%2?'#a2b998':'#91ae88');round(937+i*15,-20,20,440+(i%2)*18,10,i%2?'#a2b998':'#91ae88');}
  ellipse(500,466,480,207,'#c4ac7d');ellipse(500,442,480,207,'#e4cfa1');ellipse(500,435,480,198,'#e9d8b2');for(let y=350;y<610;y+=27)line([[95+(y-430)*.22,y],[905-(y-430)*.22,y]],'#c7b28566',1.3);
  for(const x of [170,330,500,670,830]){line([[x,0],[x,68+(x%3)*8]],'#899d75',1.5);ellipse(x,95,44,54,'#f8e4a52b');round(x-12,67,24,37,10,'#e9d193','#a3a577');}
  for(const [x,y] of [[230,290],[500,245],[770,290]]){const glow=ctx.createRadialGradient(x,y,5,x,y,155);glow.addColorStop(0,'#fff9db60');glow.addColorStop(1,'#fff9db00');ellipse(x,y,160,190,glow);}
  round(333,111,334,37,15,'#f4eccf','#b6bf9f');ctx.fillStyle='#667d58';ctx.textAlign='center';ctx.font='19px Georgia';ctx.fillText('THE RICE ORCHESTRA',500,136);
  const positions=[[225,345],[500,315],[775,345],[305,475],[715,475]];
  for(const [i,p] of band().entries()){const [x,y]=positions[i];ellipse(x,y+3,58,13,'#78865a24');const active=audio.running&&audio.performance(p.id).hit>.2;if(active&&!reduced.matches)ellipse(x,y+3,62,16,'#fff7cf40');drawPerformer(p.id,x,y,145);line([[x+86,y-2],[x+86,y-65]],'#8b9470',3);line([[x+68,y],[x+86,y-6],[x+102,y]],'#8b9470',2);round(x+63,y-91,48,32,4,'#fff6db','#a4ad8a');line([[x+70,y-81],[x+103,y-81]],'#c7cbaa',1);line([[x+70,y-72],[x+103,y-72]],'#c7cbaa',1);ctx.fillStyle='#778364';ctx.font='12px system-ui';ctx.fillText(p.name.split(' ').slice(0,2).join(' '),x,y+25);}
  ellipse(500,605,150,28,'#b59c73');round(369,582,262,25,8,'#d4bc8e','#baa16f');drawPerformer('choir',500,590,240);
  ctx.fillStyle='#786e50';ctx.font='12px system-ui';ctx.fillText('Rice Grain Choir · conducting',500,637);
  if(!reduced.matches&&!paused)for(let i=0;i<7;i++){const x=135+i*117+Math.sin(stageTime+i)*8,y=340-((stageTime*21+i*47)%160);ctx.fillStyle=['#a88c58','#8ea576','#b69b7e'][i%3];ctx.font='18px Georgia';ctx.fillText(i%2?'♪':'♫',x,y);}
 }
 function resize(){const rect=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(rect.width&&rect.height){canvas.width=Math.round(rect.width*d);canvas.height=Math.round(rect.height*d);}draw();}window.addEventListener('resize',resize);
 function frame(now){const dt=Math.min((now-lastFrame)/1000||0,.05);lastFrame=now;if(screen==='concert'&&!paused){audio.tick();if(audio.running)stageTime=Math.max(0,audio.context.currentTime-audio.startedAt);const phrase=Math.floor(audio.step/32);$('form').textContent=SoundGardenComposer.sectionFor(audio.song,phrase).form;}draw();requestAnimationFrame(frame);}
 songInfo();renderSelection();requestAnimationFrame(frame);
})();
